import requests

# User-Agent: Identifies the user agent (typically a web browser or an application) making the request.
# Accept: Indicates the MIME types acceptable in the response. It specifies the file formats the client can handle.
# Accept-Language: Specifies the preferred language of the response. It indicates the language in which the client wants the response to be presented.
# Connection: Specifies whether the connection to the server should be kept alive or closed after the response is received.
# Referer: Provides the URL of the page that referred the client to the current URL.

#
headers = {
    'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.246',
    'Accept':'text/html',
    'Accept-Language':'en-US',
    'Connection': 'keep-alive',
    'Referer':'https://www.google.com/',
}

response= requests.get('https://www.3m.com/3M/en_US/p/c/abrasives/',headers=headers)

# Date: Specifies the date and time when the response was generated by the server.
# Server: Identifies the software server used by the website to handle the request.
# Content-Type: Specifies the MIME type of the response content. For example, "text/html" for HTML content.
# Content-Length: Indicates the length of the response body in bytes.
# Cache-Control: Specifies caching directives for the client and any intermediate caches.

'''
These are just a few examples of the headers that can be included in a request or response. 
Different headers serve different purposes and provide various information to 
facilitate communication between the client (browser or application) and the server.
'''
print(response.status_code)
print('\n')
print(response.headers)
print('\n\n')
print(response.headers['Content-Type'])
print(response.headers['Content-Length'])
print(response.headers['Date'])
print(response.headers['Server'])
print(response.headers['Cache-Control'])
